### ISSUE TITLE
Minor suggestions for installation instructions on Windows

### ISSUE THREAD

**Issue by rsignell-usgs** [EarthBigData/openSAR#1]
When you run the miniconda installer on windows, you must make choices on whether to add miniconda to the system path and registry.   Recommend *not* doing that (unchecking the two boxes), so that you can keep your system clean, like on Mac and Linux.   To work with conda python, you then fire up a Anaconda command prompt window, which adds miniconda to the path.   From there you can type your conda commands.  

If you don't do this, you can have python conflict problems.

Don't you want folks to git clone the repo or download the zip file, then `cd` to the directory where the `ebd_env .yml` file is and create the `ebd` environment? 

The tests worked perfectly for me:
![09](https://user-images.githubusercontent.com/1872600/35097355-c18cf2e8-fc1d-11e7-9b12-8b4a67c8dddd.png)

**Comment by jkellndorfer** [comment]
thanks. Incorporated in the installation instructions.
