### ISSUE TITLE
Getting custom environments to appear in Jupyter kernel list on windows

### ISSUE THREAD

**Issue by rsignell-usgs** [EarthBigData/openSAR#2]
@jkellndorfer , okay we spent hours last night trying to get this to work with Miniconda and failed, right?

We should have just read the IOOS environment instructions by Filipe @ocefpaf  at
http://ioos.github.io/notebooks_demos/other_resources/
because we missed a step.

After installing miniconda, we should have done:
```
conda config --add channels conda-forge --force
conda update --all  -y
conda install  nb_conda_kernels -y
conda env create -f cond_edb.yml -q --force
```

The `conda update --all`  step is important because it updates all the packages to conda-forge.

The above works.  Proof:
![2018-01-19_10-11-50](https://user-images.githubusercontent.com/1872600/35157575-64ac1e7e-fd02-11e7-9b00-92447c7ba4ee.png)

**Comment by jkellndorfer** [comment]
Great. I’ll change the installation instructions .Thanks!

**Comment by jkellndorfer** [comment]
Did Filipe have instructions on how to bundle and install from a memory stick?

**Comment by ocefpaf** [comment]
I see that @rsignell-usgs already answered that one via e-mail but here it is for completeness in case someone looks for it in this issue:

https://conda.io/docs/user-guide/tasks/create-custom-channels.html

One alternative is to create your own installable "miniconda-like" distribution with conda-constructor:

https://github.com/conda/constructor

My experiences with constructor in the past where not good but that was one year ago and maybe the project evolved.

**Comment by josef-ebd** [comment]
Hi Filipe, 

I tried condo-constructor, but didn’t succeed either. So, now for the first method:
I have all the packages (..bz2 files) from the install and creation of the environment to build a channel with,  but the pkgs directory also contains still the non-conda-forge bz2 files that I assume came with Miniconda. I assume I would have to delete all those that didn’t come from conda-forge before building the channel. Is that’s how you do it? 

Thanks, Josef

**Comment by ocefpaf** [comment]
> I tried condo-constructor, but didn’t succeed either.

I guess that `constructor` is not mature enough yet.

>  I assume I would have to delete all those that didn’t come from conda-forge before building the channel. Is that’s how you do it?

No, I leave them all there. Let me know if that approach does not work for you.

**Comment by jkellndorfer** [comment]
Ok. That will be the approach once it actually runs. Still no luck in seeing any kernels. I installed the extensions, but that did not make a difference.

**Comment by jkellndorfer** [comment]
Ok, I was able to make it work in Windows with:

> activate ebd
> conda install nb_conda_kernels. # if it was not installed yet with the updated conda_ebd.yml
> jupyter notebook

**Comment by rsignell-usgs** [comment]
Well, at least **something** works.   

But I still want my kernels available for selection in the notebook, they way it worked *just 5 days ago*:


![2018-01-19_15-32-35](https://user-images.githubusercontent.com/1872600/35353106-25b88fe8-0114-11e8-89d5-43f8432095b5.png)

**Comment by josef-ebd** [comment]
I agree. It needs to work again …
____________________



On Jan 24, 2018, at 2:38 PM, Rich Signell <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, at least something works.

But I still want my kernels available for selection in the notebook, they way it worked just 5 days ago:

[2018-01-19_15-32-35]<https://user-images.githubusercontent.com/1872600/35353106-25b88fe8-0114-11e8-89d5-43f8432095b5.png>

**Comment by ocefpaf** [comment]
`jupyter_client 5.2.2` for Windows just got uploaded to the channel. Can you try it again and let me know? I suspect that it should work without the `nb_conda_kernels` patch, if not I will work on it tomorrow.

**Comment by jkellndorfer** [comment]
great. Is this a Windows only issue or is Linux affected as well? I have not reinstalled in Linux.

**Comment by rsignell-usgs** [comment]
On Windows, just did:
```
activate root
conda install jupyter_client
jupyter notebook
```
and.....  :champagne:  :champagne:  :champagne: 

![2018-01-24_14-57-43](https://user-images.githubusercontent.com/1872600/35354086-15a1e50c-0117-11e8-8947-4dfad739aead.png)

**Comment by ocefpaf** [comment]
Thanks to @minrk for fixing `jupyter_client`  in https://github.com/jupyter/jupyter_client/pull/339!

**Comment by rsignell-usgs** [comment]
I just did
```
activate root
conda install terminado
jupyter notebook
```
to get the terminal support, just to complete the Jupyter experience.  No more "Terminals Unavailable":

![2018-01-24_15-03-24](https://user-images.githubusercontent.com/1872600/35354369-cda564f8-0117-11e8-96bb-099439d1bba6.png)
