### ISSUE TITLE
Error during istallation on Mac OS

### ISSUE THREAD

**Issue by cpedraza79** [EarthBigData/openSAR#3]
@jkellndorfer I went trough the installation instructions and in the installation test I have an error and I don't see the image bellow. During the installation the terminal didn't show any error.
Any sugestion?

<img width="960" alt="imagen" src="https://user-images.githubusercontent.com/43978237/47466239-f4264000-d7b5-11e8-9278-e86cafbc9d64.png">

**Comment by jkellndorfer** [comment]
Hi Carlos,
That should actually be a markdown cell and not a code cell to execute.

Best,
Josef

Sent from my iPhone

On Oct 24, 2018, at 6:55 PM, Carlos Pedraza <notifications@github.com<mailto:notifications@github.com>> wrote:


@jkellndorfer<https://github.com/jkellndorfer> I went trough the installation instructions and in the installation test I have an error and I don't see the image bellow. During the installation the terminal didn't show any error.
Any sugestion?

[imagen]<https://user-images.githubusercontent.com/43978237/47466239-f4264000-d7b5-11e8-9278-e86cafbc9d64.png>

**Comment by cpedraza79** [comment]
Thanks!! Those kind of things happen when you start coding

Best,
Carlos
