### ISSUE TITLE
Missing package in step-1-1-slc2bursts.py

### ISSUE THREAD

**Issue by sergiovitale** [EarthBigData/openSAR#8]
I was trying to use the scripts you provide for creating the dataset in */code/global_coherence/*.
I have collected a list of slc files and try to run the script **step-1-1-slc2bursts.py**

When I run it, an error occure: it says me the **py_gamma** package is missing.
How can I import it?

Thanks.

**Comment by jkellndorfer** [comment]
py_gamma is part of the Gamma Software for which you would need a license. See https://gamma-rs.ch


On Aug 25, 2022, at 7:02 AM, Sergio Vitale ***@***.***> wrote:

﻿

I was trying to use the scripts you provide for creating the dataset in /code/global_coherence/.
I have collected a list of slc files and try to run the script step-1-1-slc2bursts.py

When I run it, an error occure: it says me the py_gamma package is missing.
How can I import it?

Thanks.

**Comment by sergiovitale** [comment]
Ok, thanks for the fast reply.

By using the notebooks you kindle provided, we can get as output the estimated coherence, the amplitude data as well as the metrics rho, tau, incidence angle and so on.
Is it possible to access also to co-registered DEM and SLCs or are not free available?

**Comment by jkellndorfer** [comment]
We have not retained the co-registered DEMs, but  used the global 1 arcsec Copernicus DEM as reference DEM. We kept the co-registered SLCs in burst geometry as described in the paper (https://www.nature.com/articles/s41597-022-01189-6), but retrieval requires a case-by-case  handling and is this not freely available. If you are interested in a specific region or subset of the co-registered SLCs, please contact us directly via info@earthbigdata.com
